import dynamic from 'dva/dynamic';
// wrapper of dynamic
const dynamicWrapper = (app, models, component) => dynamic({
  app,
  models: () => models.map(m => import(`../models/${m}.js`)),
  component,
});

// nav data
export const getNavData = app => [
  {
    component: dynamicWrapper(app, ['user', 'login'], () => import('../layouts/BasicLayout')),
    layout: 'BasicLayout',
    name: '首页', // for breadcrumb
    path: '/',
    children: [
      {
        name: '工作台',
        icon: 'dashboard',
        path: 'workplace',
        show: true,
        component: dynamicWrapper(app, ['workplace'], () => import('../routes/Workplace/Workplace')),
      },
      {
        name: 'Mobi C2C',
        icon: 'swap',
        path: 'c2c',
        show: true,
        children: [
          {
            name: '个人信息',
            path: 'customer/:id',
            icon: 'user',
            show: false,
            component: dynamicWrapper(app, ['customer'], () => import('../routes/C2C/Customer')),
            permissionUrl: '/v1/mtm/customer_search',
          },
          {
            name: '控制台',
            icon: 'dashboard',
            path: 'dashboard',
            show: true,
            component: dynamicWrapper(app, ['dashboard', 'customer'], () => import('../routes/C2C/Dashboard/Dashboard')),
            permissionUrl: '/v1/mtm/customer_search',
          },
          {
            name: '广告列表',
            path: 'advertising-list',
            icon: 'team',
            show: true,
            component: dynamicWrapper(app, ['advertising'], () => import('../routes/C2C/Advertising/AdList')),
            permissionUrl: '/v1/mtm/ads',
          },
          {
            name: '广告详情',
            path: 'advertising-detail/:advertisingId',
            show: false,
            component: dynamicWrapper(app, ['advertising'], () => import('../routes/C2C/Advertising/AdDetail')),
          },
          {
            name: '订单列表',
            icon: 'tags-o',
            show: true,
            path: 'order-list',
            component: dynamicWrapper(app, ['order'], () => import('../routes/C2C/Order/OrderList')),
            permissionUrl: '/v1/mtm/orders',
          },
          {
            name: '订单详情',
            show: false,
            path: 'order-detail/:orderId',
            component: dynamicWrapper(app, ['order'], () => import('../routes/C2C/Order/OrderDetail')),
          },
          {
            name: '申诉表格',
            icon: 'solution',
            path: 'complaint-table',
            show: true,
            component: dynamicWrapper(app, ['complaint'], () => import('../routes/C2C/List/TableList')),
            permissionUrl: '/v1/mtm/order_complaints',
          },
          {
            name: '申诉详情',
            path: 'complaint-details/:id',
            show: false,
            component: dynamicWrapper(app, ['complaint'], () => import('../routes/C2C/Complaint')),
          },
          {
            name: '设置',
            icon: 'setting',
            path: 'setting',
            show: true,
            component: dynamicWrapper(app, ['setting'], () => import('../routes/C2C/Setting/Setting')),
            permissionUrl: '/v1/mtm/system_setting',
          },
          {
            name: '异常',
            path: 'exception',
            icon: 'warning',
            children: [
              {
                name: '403',
                path: '403',
                component: dynamicWrapper(app, [], () => import('../routes/C2C/Exception/403')),
              },
              {
                name: '404',
                path: '404',
                component: dynamicWrapper(app, [], () => import('../routes/C2C/Exception/404')),
              },
              {
                name: '500',
                path: '500',
                component: dynamicWrapper(app, [], () => import('../routes/C2C/Exception/500')),
              },
            ],
          },
        ],
      },
      {
        name: '平台资产管理',
        icon: 'home',
        path: 'assets-management',
        show: true,
        children: [
          {
            name: '当前资产概览',
            path: 'dashboard',
            show: true,
            component: dynamicWrapper(app, ['assets'], () => import('../routes/Assets/Dashboard/Dashboard')),
            permissionUrl: '/v1/dashboard/index',
          },
          {
            name: '每日资产变更',
            path: 'daily-assets-change',
            show: true,
            component: dynamicWrapper(app, ['assets'], () => import('../routes/Assets/DailyAssetsChange')),
            permissionUrl: '/v1/dashboard/asset_change',
          },
          {
            name: '汇率概览',
            path: 'rate-view',
            show: true,
            component: dynamicWrapper(app, ['assets'], () => import('../routes/Assets/RateView')),
            permissionUrl: '/v1/dashboard/rate',
          },
          {
            name: '每日货币兑换总量变更',
            path: 'daily-currency-exchange-change',
            show: true,
            component: dynamicWrapper(app, ['assets'], () => import('../routes/Assets/DailyCurrenyExchangeChange')),
            permissionUrl: '/v1/dashboard/exchange_flow',
          },
          {
            name: '货币兑换交易记录',
            path: 'currency-exchange-history',
            show: true,
            component: dynamicWrapper(app, ['assets'], () => import('../routes/Assets/CurrencyExchangeHistory')),
            permissionUrl: '/v1/dashboard/exchange_transaction_recode',
          },
        ],
      },
      {
        name: '用户管理',
        icon: 'user',
        path: 'user-management',
        show: true,
        children: [
          {
            name: '用户列表',
            path: 'user-list',
            show: true,
            component: dynamicWrapper(app, ['usermanagement'], () => import('../routes/UserManagement/UserList')),
            permissionUrl: '/v1/customers_search',
          },
          {
            name: '详细信息',
            path: 'user-detail/:id',
            show: false,
            component: dynamicWrapper(app, ['userdetail', 'customer'], () => import('../routes/UserManagement/UserDetail')),
          },
        ],
      },
      {
        name: '交易管理',
        icon: 'profile',
        path: 'trade-management',
        show: true,
        children: [
          {
            name: '全部交易',
            path: 'allTransaction',
            show: true,
            component: dynamicWrapper(app, ['transaction'], () => import('../routes/Transaction/AllTransaction/AllTransactionList')),
            permissionUrl: '/v1/transaction',
          },
          {
            name: '全部交易详情',
            path: 'allTransaction-details/:id',
            show: false,
            component: dynamicWrapper(app, ['transaction'], () => import('../routes/Transaction/AllTransaction/AllTransactionDetail')),
          },
          {
            name: 'On-chain收发',
            path: 'onchainTransaction',
            show: true,
            component: dynamicWrapper(app, ['transaction'], () => import('../routes/Transaction/OnchainTransaction/OnchainTransactionList')),
            permissionUrl: '/v1/transaction/onchain',
          },
          {
            name: 'On-chain收发详情',
            path: 'onchainTransaction-details/:id',
            show: false,
            component: dynamicWrapper(app, ['transaction'], () => import('../routes/Transaction/OnchainTransaction/OnchainTransactionDetail')),
          },
          {
            name: '货币兑换交易记录',
            path: 'exchangeTransaction',
            show: true,
            component: dynamicWrapper(app, ['transaction'], () => import('../routes/Transaction/ChangeTransaction/ChangeTransactionList')),
            permissionUrl: '/v1/transaction/exchange',
          },
          {
            name: '货币兑换详情',
            path: 'exchangeTransaction-details/:id',
            show: false,
            component: dynamicWrapper(app, ['transaction'], () => import('../routes/Transaction/ChangeTransaction/ChangeTransactionDetail')),
          },
          {
            name: 'Mobi 转账',
            path: 'mobiTransaction',
            show: true,
            component: dynamicWrapper(app, ['transaction'], () => import('../routes/Transaction/MobiTransaction/MobiTransactionList')),
            permissionUrl: '/v1/transaction/mobi',
          },
          {
            name: 'Mobi 转账详情',
            path: 'mobiTransaction-details/:id',
            component: dynamicWrapper(app, ['transaction'], () => import('../routes/Transaction/MobiTransaction/MobiTransactionDetail')),
          },
        ],
      },
      {
        name: '对冲管理',
        icon: 'bank',
        show: true,
        path: 'hedging',
        children: [
          {
            name: '实时监控',
            show: true,
            path: 'monitor',
            component: dynamicWrapper(app, ['hedging'], () => import('../routes/Hedging/Monitor')),
            permissionUrl: '/v1/hedge/hedge_monitor',
          },
          {
            name: '对冲记录',
            show: true,
            path: 'hedging-record/:currency',
            component: dynamicWrapper(app, ['hedging'], () => import('../routes/Hedging/History')),
            permissionUrl: '/v1/hedge/hedge_records',
          },
          {
            name: '设置',
            show: true,
            path: 'setting',
            component: dynamicWrapper(app, ['hedging'], () => import('../routes/Hedging/Setting')),
            permissionUrl: '/v1/hedge/hedge_platform',
          },
        ],
      },
      {
        name: '财务管理',
        icon: 'pay-circle-o',
        show: true,
        path: 'financial',
        children: [
          {
            name: '财务报表',
            show: true,
            path: 'financialList',
            component: dynamicWrapper(app, ['financialList'], () => import('../routes/Financial/financialList')),
            permissionUrl: '/v1/financial/fiat/exchange',
          }, {
            name: '审计报表',
            show: true,
            path: 'auditReport',
            component: dynamicWrapper(app, ['auditReport'], () => import('../routes/Financial/auditReport')),
            permissionUrl: '/v1/assets',
          },
        ],
      },
      {
        name: '现金充提',
        icon: 'swap',
        show: true,
        path: 'cashCharge',
        children: [
          {
            name: '充值请求',
            show: true,
            path: 'deposit',
            component: dynamicWrapper(app, ['cashManage'], () => import('../routes/CashManage/deposit')),
            permissionUrl: '/v1/deposit/list',
          },
          {
            name: '新增充值',
            show: false,
            path: 'addDeposit',
            component: dynamicWrapper(app, ['cashManage'], () => import('../routes/CashManage/deposit/addDeposit')),
            permissionUrl: '/v1/deposit/detail',
          },
          {
            name: '提现请求',
            show: true,
            path: 'widthdraw',
            component: dynamicWrapper(app, ['cashManage'], () => import('../routes/CashManage/widthdraw')),
            permissionUrl: '/v1/withdraw/list',
          },
          {
            name: '新增提现',
            show: false,
            path: 'addWidthdraw',
            component: dynamicWrapper(app, ['cashManage'], () => import('../routes/CashManage/widthdraw/addWidthdraw')),
            permissionUrl: '/v1/withdraw/detail',
          },
        ],
      },
      {
        name: '币丰堂',
        icon: 'pay-circle-o',
        show: true,
        path: 'yubibao',
        children: [
          {
            name: '转入转出记录',
            show: true,
            path: 'recording',
            component: dynamicWrapper(app, ['yubiBao'], () => import('../routes/Yubibao/recording')),
            permissionUrl: '/yub/web/rate/list',
          },
          {
            name: '币丰堂设置',
            show: true,
            path: 'settings',
            component: dynamicWrapper(app, ['yubiBao'], () => import('../routes/Yubibao/settings')),
            permissionUrl: '/yub/web/daily/setting',
          },
        ],
      },
      {
        name: 'KYC',
        icon: 'tool',
        path: 'kyc',
        show: true,
        children: [
          {
            name: '实名认证',
            show: true,
            path: 'verified',
            component: dynamicWrapper(app, ['usermanagement'], () => import('../routes/KYC/Verified/VerifiedList')),
            permissionUrl: '/v1/customers_search',
          },
          {
            name: '已归档列表',
            show: true,
            path: 'yiList',
            component: dynamicWrapper(app, ['NameCertification'], () => import('../routes/KYC/NameCertification/yiList')),
            permissionUrl: '/v1/customers_search',
          },
          {
            name: '证件验证',
            show: false,
            path: 'DocumentVerification/:id',
            component: dynamicWrapper(app, ['NameCertification'], () => import('../routes/KYC/NameCertification/yiList/DocumentVerification.js')),
            permissionUrl: '/v1/customers_search',
          },
          {
            name: '地址验证',
            show: false,
            path: 'addressVerification/:id',
            component: dynamicWrapper(app, ['NameCertification'], () => import('../routes/KYC/NameCertification/yiList/addressVerification.js')),
            permissionUrl: '/v1/customers_search',
          },
          {
            name: '详细信息',
            show: true,
            path: 'detail/:type',
            component: dynamicWrapper(app, ['userdetail', 'customer'], () => import('../routes/KYC/Verified/VerifiedDetail')),
          },
        ],
      },
      {
        name: '后台管理',
        icon: 'tool',
        path: 'back-management',
        show: true,
        children: [
          {
            name: '后台权限',
            show: true,
            path: 'auth',
            children: [
              {
                name: '用户权限列表',
                show: true,
                path: 'userAuthList',
                component: dynamicWrapper(app, ['backManagement'], () => import('../routes/BackManagement/RolesList')),
                permissionUrl: '/v1/admin_users',
              },
              {
                name: '角色群组列表',
                show: false,
                path: 'grouproleList',
                component: dynamicWrapper(app, ['transaction'], () => import('../routes/Transaction/MobiTransaction/MobiTransactionDetail.js')),
              },
              {
                name: '群组权限列表',
                show: false,
                path: 'groupAuthList',
                component: dynamicWrapper(app, ['transaction'], () => import('../routes/Transaction/MobiTransaction/MobiTransactionDetail.js')),
              },
              {
                name: '添加/编辑群组',
                show: true,
                path: 'addOrEditGroup',
                component: dynamicWrapper(app, ['backManagement'], () => import('../routes/BackManagement/addOrEditGroup/')),
                permissionUrl: '/v1/admin_role',
                permissionMethod: 'POST', // todo
              },
              {
                name: '添加/编辑权限',
                show: false,
                path: 'addOrEditRole/:roleName',
                component: dynamicWrapper(app, ['backManagement'], () => import('../routes/BackManagement/addOrEditRole/')),
              },
            ],
          },
          {
            name: '后台日志',
            show: true,
            path: 'log',
            component: dynamicWrapper(app, ['backManagement'], () => import('../routes/BackManagement/Log/index.js')),
            permissionUrl: '/v1/operation_logs',
          },
          {
            name: '后台设置',
            show: true,
            path: 'setting',
            component: dynamicWrapper(app, ['setting'], () => import('../routes/C2C/Setting/Setting.js')),
            permissionUrl: '/v1/mtm/system_setting',
          },
        ],
      },
      {
        name: '商户管理',
        icon: 'pay-circle-o',
        show: true,
        path: 'bussniess',
        children: [
          {
            name: '商户列表',
            show: true,
            path: 'bussniessList',
            component: dynamicWrapper(app, ['bussinessList', 'bussinessDetail'], () => import('../routes/BussinessManage/bussinessList/index.js')),
            permissionUrl: '/business/platform_info',
          },
          {
            name: '商户详情',
            path: 'bussniessDetail/:id',
            show: false,
            component: dynamicWrapper(app, ['bussinessDetail'], () => import('../routes/BussinessManage/BussinessDetail/index.js')),
          },
          {
            name: '设置',
            path: 'bussniessSettings',
            show: true,
            component: dynamicWrapper(app, ['bussinessSetting'], () => import('../routes/BussinessManage/BussinessSetting/index.js')),
            permissionUrl: '/business/setting',
          },
        ],
      },
    ],
  },
];
